language: php
php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5
  - 5.6
env:
  - COMPOSER=composer.json
  - COMPOSER=composer-37.json
matrix:
  include:
    - php: hhvm
      env: COMPOSER=composer-hhvm.json
    - php: 5.6
      env: PHPUNIT_OPTIONS="--coverage-clover build/logs/clover.xml"

install:
  - composer install
script:
  - phpunit $PHPUNIT_OPTIONS

after_script:
  - "if [[ ! -f build/logs/clover.xml ]] ; then php vendor/bin/coveralls -v; fi"
  - "if [[ ! -f build/logs/clover.xml ]] ; then wget https://scrutinizer-ci.com/ocular.phar; fi"
  - "if [[ ! -f build/logs/clover.xml ]] ; then php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml; fi"
